FOLDER: './experiments' # Experiment files saving path

TEST:
  FOLDER: './results' # Testing files saving path

DATASET:
  BEATDND:
    ROOT: ['./datasets/beat_english_v0.2.1/', './datasets/utterance_dataset_5sec/']
    SPLIT_ROOT: ['./datasets/beat_english_v0.2.1/', './datasets/utterance_dataset_5sec/']
    VAE_SPLIT_ROOT: ['.datasets/beat_english_v0.2.1/', './datasets/utterance_dataset_5sec/']
    KINEMATIC_TREE: [[0, 4, 3, 2, 1], [0, 18, 19, 20, 21, 22], [0, 13, 14, 15, 16, 17], [3, 9, 10, 11], [3, 5, 6, 7] , [7, 23, 24, 25, 26], [7, 27, 28, 29, 30], [7, 8, 31, 32, 33, 34], [7, 35, 36, 37, 38], [7, 39, 40, 41, 42], [11, 43, 44, 45, 46], [11, 47, 48, 49, 50], [11, 12, 51, 52, 53, 54], [11, 55, 56, 57, 58], [11, 59, 60, 61, 62]]
    BONES: [[0, 4], [4, 3], [3, 2], [2, 1], [0, 18], [18, 19], [19, 20], [20, 21], [21, 22], [0, 13], [13, 14], [14, 15], [15, 16], [16, 17], [3, 9], [9, 10], [10, 11], [3, 5], [5, 6], [6, 7], [7, 23], [23, 24], [24, 25], [25, 26], [7, 27], [27, 28], [28, 29], [29, 30], [7, 8], [8, 31], [31, 32], [32, 33], [33, 34], [7, 35], [35, 36], [36, 37], [37, 38], [7, 39], [39, 40], [40, 41], [41, 42], [11, 43], [43, 44], [44, 45], [45, 46], [11, 47], [47, 48], [48, 49], [49, 50], [11, 12], [12, 51], [51, 52], [52, 53], [53, 54], [11, 55], [55, 56], [56, 57], [57, 58], [11, 59], [59, 60], [60, 61], [61, 62]]
    OFFSET_NPY_PATH: ./datasets/beat_english_v0.2.1/sample_offsets.npy
  

model:
  t5_path: 't5-base'
  weg_parameters:
    scale_factor: 1000
    scale_range: [1., 0.5]
    max_iter_to_alter: 800
    thresholds: {0: 0.05, 200: 0.4, 400: 0.6, 600:0.8}
    max_refinement_steps: 300