####################################
# The following are general settings
####################################

# Experiment name, more details in Section 'Experiment Name Explanation'
NAME: test #beatdndspk_joints_rld_lat2x128_mixatt_ddpm_uncond01_gs75_tspksmol_talsn_timechunk8vaeapb_bhposbhembed_timeaddnlayer_rootposfixrbwristnorm_textmaskfix_conditionid_lowaudionoise_bs32_dropexceptcond_eosbos #1222_PELearn_Diff_Latent1_MEncDec49_MdiffEnc49_bs64_clip_uncond75_01
# Debug mode. Set to True will enter the debug mode, then the program will
# 1. use a tiny dataset for trianing and evaluation
# 2. validate more intensively
# 3. will not use `wandb logger`
DEBUG: False
# Devices. Optional: “cpu”, “gpu”
ACCELERATOR: 'gpu'
# Index of GPUs eg. [0] or [0,1,2,3]
DEVICE: [0]

#####################################
# The following are training settings
#####################################
TRAIN:
  # Model stage. Optional: "vae", "diffusion"
  STAGE: diffusion
  # Training dataset name
  DATASETS: ['beatdnd']
  # Number of dataloader workers

  NUM_WORKERS: 5
  # Size of batches
  BATCH_SIZE: 64
  # Total epochs for training
  START_EPOCH: 0
  END_EPOCH: 2000
  

  RESUME: '' # Resume training from this path
  PRETRAINED_VAE: './experiments/mld/beatdnd_joints_vae_lat2x128_len128_lkl_handsc_timechunk8_rootposfix_rb_bonelenlossonlyframes2_wristnormchange/checkpoints/epoch=989.ckpt' # vae model path
  OPTIM:
    TYPE: AdamW # Optimizer type
    LR: 7e-5 # Learning rate
  # Ablation study configurations.
  ABLATION:
    WEG_TYPE: semantic # semantic or random
    SKIP_CONNECT: True
    PE_TYPE: convofusion
    DIFF_PE_TYPE: convofusion
    PREDICT_EPSILON: True # noise (true) or motion (false)
    MLP_DIST: False
    CAUSAL_ATTN: False # causal attention

#####################################
# The following are validation settings
#####################################
EVAL:
  DATASETS: ['beatdnd'] # Evaluating datasets
  BATCH_SIZE: 32 # Evaluating Batch size
  SPLIT: val

#####################################
# The following are testing settings
#####################################
TEST:
  CHECKPOINTS: '' # Pretrained model path
  DATASETS: ['beatdnd'] # training datasets
  SPLIT: val
  BATCH_SIZE: 32 # training Batch size
  MEAN: False
  NUM_SAMPLES: 1
  FACT: 1
  SAVE_PREDICTIONS: True
  DIVERSITY_TIMES: 2

#####################################
# The following are basic datasets settings
#####################################
DATASET:
  JOINT_TYPE: 'beatdnd' # join type
  SAMPLER:
    MAX_LEN: 128
    MIN_LEN: 128
  BEATDND:
    SELECT: 'both' # 'beat' or 'dnd' or 'both'
    POSE_REP: 'pos'
    UNIT_LEN: 1
    SR: 16000
    N_MELS: 80
    HOP_LEN: 512
    FPS: 25
    FACE_JOINT_IDX: [18, 13, 9, 5]


#####################################
# The following are metric settings
#####################################
METRIC:
  TYPE: [] #['TM2TMetrics', 'UncondMetrics'] #['TemosMetric', 'TM2TMetrics']

#####################################
# The following are training losses settings
#####################################
LOSS:
  TYPE: convofusion # Losses type
  LAMBDA_LATENT: 0.0 #1.0e-1 # 1.0e-2 # Lambda for latent Losses
  LAMBDA_KL: 5.0e-2 # Lambda for kl Losses
  LAMBDA_REC: 5.0 # Lambda for reconstruction Losses
  LAMBDA_GEN: 0.0 #1.0e-1 # Lambda for text-motion generation losses
  LAMBDA_CROSS: 1.0 # Lambda for reconstruction Losses
  LAMBDA_CYCLE: 0.0 # Lambda for cycle Losses
  LAMBDA_PRIOR: 0.0
  LAMBDA_GUIDED_ATTENTION: 0.0 #5.0e-4 # 1 e- 3
  DIST_SYNC_ON_STEP: False # Sync Losses on step when distributed trained

#####################################
# The following are basic model settings
#####################################
model:
  vae: true # whether vae model
  model_type: convofusion # model type
  condition: 'text+audio'
  latent_dim: [1, 128] # latent dimension
  ff_size: 1024 #
  num_layers: 17 # number of layers
  num_head: 8 # number of head layers
  droupout: 0.1 # dropout rate
  activation: gelu # activation type
  guidance_scale: 7.5 #
  guidance_uncondp: 0.1 # 0.1 0.25

#####################################
# The following are loggers settings
#####################################
LOGGER:
  SACE_CHECKPOINT_EPOCH: 5 # : change
  LOG_EVERY_STEPS: 1
  VAL_EVERY_STEPS: 10 # : change to 1000
  TENSORBOARD: True
  WANDB:
    PROJECT: null
    OFFLINE: False
    RESUME_ID: null
