NAME: beatdnd_joints_vae_lat2x128_len128_lkl_handsc_timechunk8_rootposfix_rb_bonelenlossonlyframes2_wristnormchange # beat_joints_vae_lat512_len128_handsrel_noego_alleq_posfix2 # beat_6d_vae_lat512_len128_scaled10 #1222_PELearn_VAE_MEncDec49_MdiffEnc49_bs64_clip_uncond75_01 # Experiment name
DEBUG: False # Debug mode
ACCELERATOR: 'gpu' # Devices optioncal: “cpu”, “gpu”, “tpu”, “ipu”, “hpu”, “mps, “auto”
DEVICE: [0] # Index of gpus eg. [0] or [0,1,2,3]

# Training configuration
TRAIN:
  #---------------------------------
  STAGE: vae # stage "vae" or "diffusion", "vae_diffusion"
  #---------------------------------
  ABLATION:
    SKIP_CONNECT: True
    PE_TYPE: convofusion
    DIFF_PE_TYPE: convofusion
    PREDICT_EPSILON: True # noise or motion
    MLP_DIST: False
  DATASETS: ['beatdnd'] # Training datasets
  NUM_WORKERS: 11 # Number of workers
  BATCH_SIZE: 128 # Size of batches
  START_EPOCH: 0 # Start epochMMOTIONENCODER
  END_EPOCH: 6000 # End epoch
  RESUME: '' # Resume training from this path
  PRETRAINED_VAE: ''
  OPTIM:
    TYPE: AdamW # Optimizer type
    LR: 1e-4 # Learning rate

# Evaluating Configuration
EVAL:
  DATASETS: ['beatdnd'] # Evaluating datasets
  BATCH_SIZE: 32 # Evaluating Batch size
  SPLIT: val

# Test Configuration
TEST:
  CHECKPOINTS: '' # Pretrained model path
  DATASETS: ['beatdnd'] # training datasets
  SPLIT: val
  BATCH_SIZE: 32 # training Batch size
  MEAN: False
  NUM_SAMPLES: 1
  FACT: 1
  REPLICATION_TIMES: 1
  SAVE_PREDICTIONS: True

# Datasets Configuration
DATASET:
  SAMPLER:
    MAX_LEN: 128
    MIN_LEN: 128
  BEATDND:
    POSE_REP: 'pos'
    UNIT_LEN: 1
    SR: 16000
    N_MELS: 80
    HOP_LEN: 512
    FPS: 25
    FACE_JOINT_IDX: [18, 13, 9, 5]

METRIC:
  TYPE: []
# Losses Configuration
LOSS:
  TYPE: convofusion # Losses type
  LAMBDA_LATENT: 1.0e-4 # Lambda for latent Losses
  LAMBDA_KL: 5.0e-2 # Lambda for kl Losses
  LAMBDA_REC: 5.0 # Lambda for reconstruction Losses
  LAMBDA_GEN: 1.0 # Lambda for text-motion generation losses
  LAMBDA_CROSS: 1.0 # Lambda for reconstruction Losses
  LAMBDA_CYCLE: 0.0 # Lambda for cycle Losses
  LAMBDA_PRIOR: 0.0
  LAMBDA_BL: 1.0
  DIST_SYNC_ON_STEP: False # Sync Losses on step when distributed trained

# Model Configuration
model:
  vae: true # whether vae model
  model_type: convofusion # model type
  condition: 'text+audio' # condition type
  latent_dim: [1, 128] # latent dimension
  ff_size: 1024 #
  num_layers: 9 # number of layers
  num_head: 4 # number of head layers
  droupout: 0.1 # dropout rate
  activation: gelu # activation type
  guidance_scale: 7.5 #
  guidance_uncondp: 0.1 # 0.1 0.25

# Logger configuration
LOGGER:
  SACE_CHECKPOINT_EPOCH: 10
  LOG_EVERY_STEPS: 1
  VAL_EVERY_STEPS: 500
  TENSORBOARD: True
  WANDB:
    PROJECT: null
    OFFLINE: False
    RESUME_ID: null
